### PR TITLE
fixed .h .c function declaration matching resulted in warnings

### PR DESCRIPTION
**Pull request by jhusak**
removed 5 warnings during compilation.

### CODE REVIEW

**Review by dmsc — APPROVED** [review]
Looks good to me.

**Comment by jhusak** [comment]
The reason:
pbi_xld.c:197:26: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]

So worth fixing.

**Comment by jhusak** [comment]
MacbookPro and clang: Apple clang version 15.0.0 (clang-1500.0.40.1)

**Comment by mikrosk** [comment]
Ah, clang then. OK, merging.

**Pull request merged**
