### PR TITLE
Tool to convert cartridge ROMs to CART files

### PR DESCRIPTION
**Pull request by wfd3**
Wrote a little tool to convert cartridge ROMs to CART files.

### CODE REVIEW

**Comment by mikrosk** [comment]
Actually this seems to be doing a lot of more than adding the tool. Was it intentional?

**Comment by wfd3** [comment]
Ah, no, it wasn't.  Sorry, it looks like I created the PR from the wrong repo.  That said, this PR contains changes I intended to submit which add support for remapping the Atari control keys (and Exit/F9) to make this work with arcade cabinet control panels.  

Sorry about this; I'll happily submit two separate PR's if you'd like.

**Comment by mikrosk** [comment]
Please do. You can force push this branch with your intended changes + create another PR with the other changes.

**Comment by wfd3** [comment]
OK, closing this PR and will open new ones.

**Pull request closed without merging**
