### PR TITLE
Add POKEY recording functionality

### PR DESCRIPTION
**Pull request by mikrosk**
It supports mono and stereo recording of the first 9 Pokey registers to a file. This can be handy for recording (Turbo) Basic tunes or songs for which it is difficult to separate the player from the game.

Contributed by Ivo van Poorten.

First feature request here: https://atariage.com/forums/topic/242349-sap-type-r-recording-turbo-basic-tunes-to-sap

Published here: https://sourceforge.net/p/atari800/mailman/message/34458219/

### CODE REVIEW

**Comment by mikrosk** [comment]
Similar patch, I don't get what is the difference: https://sourceforge.net/p/atari800/patches/5 ?

**Comment by mikrosk** [comment]
Argh, it fails because we moved from configure.ac `OBJS` to Makefile.am. @th-otto can you advise the easiest fix here?

**Comment by th-otto** [comment]
Just add pokeyrec.[ch] to the list of source files:

```
diff --git a/src/Makefile.am b/src/Makefile.am
index 89e080f..a9177cd 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -68,6 +68,7 @@ atari800_SOURCES = \
        pbi.c pbi.h \
        pia.c pia.h \
        pokey.c pokey.h \
+       pokeyrec.c pokeyrec.h \
        roms/altirra_5200_os.c roms/altirra_5200_os.h \
        rtime.c rtime.h \
        sio.c sio.h \
```
The location there is the list of source files that are always compiled, there are some others when using WITH_SOUND etc.

After that, just regenerate dependant files by running autogen.sh.

**Comment by mikrosk** [comment]
Yeah but if we want to do it conditionally? (`WANT_POKEYREC` = yes)

**Comment by th-otto** [comment]
Then just add a switch like AC_ARG_WITH([pokeyrec]) to configure.ac (just use some other switch there as example), add a AC_DEFINE(WITH_POKEYREC) that depends on that, and either use an AM_CONDITIONAL to conditionally add the files to list of source files, or just enclose the whole source file in #ifdef WITH_POKEYREC (after inclduing config.h of course)

**Comment by mikrosk** [comment]
Gosh I hate that stuff. Many thanks, I'll fix it.

While I am at it, can you explain to me another autotools mystery? When I do `make dist`, it creates a nice release tarball. However two folders, `util` and `src/libatari800` leave `.deps` folder in there. Other folders normally also contain `.deps` folder but it is skipped, except those two.

**Comment by th-otto** [comment]
For util, that is because of
```
EXTRA_DIST = $(doc_DATA) act data debian util
```
in the toplevel Makefile.am. That will just add everything in the util directory to the tarball. If you have actuallly sources there that are compiled, and thus produce tempory files, you should add a Makefile.am to that directory, add util to the SUBDIRS in the toplevel Makefile.am, add util/Makefile.am to the CONFIG_FILES in configure.ac, and then list any file that should be distributed explicitly in util/Makefile.am

When i run "make dist" here, i have only have that .deps directory in the tarball, but not the other.

**Comment by th-otto** [comment]
BTW:
```
AC_INIT(Atari800, 4.0.0, pstehlik@sophics.cz)
```
The version number is still 4.0.0. That is the one used by automake do determine the name of the archive, amongst others.

**Comment by joysfera** [comment]
@th-otto OK, will increase that version number upon next release.

**Comment by th-otto** [comment]
Hm, that util/.deps directory seems to be some leftover of a different branch? I can just delete it, and run "make dist" in the master branch without problems.

**Comment by mikrosk** [comment]
> Hm, that util/.deps directory seems to be some leftover of a different branch? I can just delete it, and run "make dist" in the master branch without problems.

It's possible you can delete it but it is certainly not a leftover, it is surely created by `./configure`.  However it must be somehow connected to the latest addition, `libatari800` (see https://github.com/atari800/atari800/pull/38) as `util/.deps` contains also `libatari800_test-libatari800_test.Po` file (and `libatari800` is the other `.deps` which made it into the archive).

**Comment by mikrosk** [comment]
@th-otto faster than me, thanks!

**Pull request merged**
