### PR TITLE
use zlib-provided crc32 if HAVE_LIBZ is defined

### PR DESCRIPTION
**Pull request by asiekierka**
This has the potential to save some code/data space (up to ~1K) in the final binary, and avoid redundant implementations of the same algorithm.

~~EDIT: Doesn't seem to work quite right - I wonder why...~~

EDIT 2 (05/06/2020): Seems to work fine! However, I cannot test every case.

### CODE REVIEW

**Comment by mikrosk** [comment]
> EDIT: Doesn't seem to work quite right - I wonder why

Well, this makes this PR then quite useless, doesn't it. ;) Please fix it or close it.

**Comment by mikrosk** [comment]
@asiekierka any chance to look at this?

**Comment by asiekierka** [comment]
Apologies, only had time to look at it now.

It's been a while. I *think* (and a brief test seems to confirm that) the [second commit](https://github.com/atari800/atari800/pull/72/commits/0a86499da55cf40038609fa19dbe981fa76238e1) fixed the issue I mentioned in the EDIT; just that I forgot to edit the PR back. (The way to test this, IIRC, is to see if some ROMs get accepted by the auto-detection).

Whether this PR is desirable to the project is another story - I looked into it for my console ports, where a small size saving and not duplicating code can make sense, but your mileage may vary.

**Comment by dmsc** [comment]
Hi!
> Apologies, only had time to look at it now.
> 
> It's been a while. I _think_ (and a brief test seems to confirm that) the [second commit](https://github.com/atari800/atari800/pull/72/commits/0a86499da55cf40038609fa19dbe981fa76238e1) fixed the issue I mentioned in the EDIT; just that I forgot to edit the PR back. (The way to test this, IIRC, is to see if some ROMs get accepted by the auto-detection).
> 
> Whether this PR is desirable to the project is another story - I looked into it for my console ports, where a small size saving and not duplicating code can make sense, but your mileage may vary.

IMHO, this is desirable.

You should squash both commits and update the PR description.

Thanks!

**Comment by mikrosk** [comment]
No need to squash it, I'll do it when merging. So are you saying it has been tested and it is ready to merge?

**Comment by asiekierka** [comment]
To the extent I could test it, yes. It seems it's only used for ROM auto-detection, so that's where I verified it. I can't guarantee it works with every ROM or case, though.

**Comment by mikrosk** [comment]
In that case, let's merge it!

**Pull request merged**
