### PR TITLE
Debian icon update

### PR DESCRIPTION
**Pull request by hatchcliff**
Antonin changed bobek/atari800-debian to add a menu and icon to the v5.0.0 Debian release.
This pull request makes equivalent changes to the debian directory used to create packages for informal release via GitHub.
One defunct remnant of an earlier menu system (debian/menu) is deleted.

### CODE REVIEW

**Comment by hatchcliff** [comment]
I originally bundled an update to debian/atari800.cfg (from v4.2.0 to v5.0.0) into PR #164, but realised later that it had nothing to do with the Icon Update and was potentially confusing.  I have reverted this change, and will make it the subject of a separate PR.

**Comment by mikrosk** [comment]
@hatchcliff I'm a little bit confused. You're linking #164 (which is his very PR), did you mean your #162 ?

Also, #162 just removes the rpi builder but I see that commit here nevertheless? Can you take a look again at those two PRs / branches?

**Comment by hatchcliff** [comment]
Sorry for the confusion, my inexperience with GitHub is showing up here.  I attempted to create two separate pull requests, #162 and #164, but something went wrong and they are clearly linked.  Can you merge them in their current state?  If not, let me know, and I will close them and resubmit one at a time.

**Comment by mikrosk** [comment]
No worries, I can handle the commits, just tell me what was your intention. Right now we have these three commits in this PR:

[remove rpi builder](https://github.com/atari800/atari800/pull/164/commits/eae20d839ba674391cae2fa87f5e333e115fb762)
[Debian Icon Update](https://github.com/atari800/atari800/pull/164/commits/367364af6c7421553448b4eefe2bd5629231ff58)
[Add debian/atar800.desktop](https://github.com/atari800/atari800/pull/164/commits/81d9a0b2898023793e786ddd3654726bb44a34a2)

Did you want to remove the first one and keep the other two here? (and move the first one to #162?)

**Comment by hatchcliff** [comment]
Thank you.
Yes, that's exactly what I intended:
'remove rpi builder' on #162 
'Debian Icon Update' and 'Add debian/atari800.desktop' on #164

**Comment by mikrosk** [comment]
All merged, thanks!

**Pull request merged**
